---
title: "RecipeSharingSite API"
output:
  html_document:
    toc: true
    toc_float: true
    theme: readable
---

<style>
pre {
  max-height: 400px;
  width: 910px;
  overflow-x: auto;
  overflow-y: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
hr {
  border: none;
  height: .25em;
  width: 910px;
  background-color: #e1e4e8
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width=200)
options(height=400)
```

# Users

## Get list of users

```{js}
GET /users/
```


#### Parameters

None

#### Default Response

```{js}
Status: 200 OK
```

```{js}
{
   "users":[
      {
         "comments":[
            2,
            6
         ],
         "email":"testuser1@gmail.com",
         "id":1,
         "name":"Test User 1",
         "recipes":[
            1
         ]
      },
      {
         "comments":[
            1,
            4
         ],
         "email":"TU2@gmail.com",
         "id":2,
         "name":"Test User 2",
         "recipes":[
            2
         ]
      },
   ]
}
```

---

## Get information on user

```{js}
GET /users/{user_name}
```

#### Parameters

| Name      | Type    | In   | Description |
|-----------|---------|------|-------------|
| user_name | string  | path |             |

#### Default Response
```{js}
Status: 200 OK
```

```{js}
{
   "user_id": 1,
   "name": "TestUser1",
   "email": "testuser1@gmail.com",
   "joined_on": "2000-06-23"
   "recipes": [
      1
   ],
   "comments": [
      2,
      6
   ]
}


```
---

## Add user

```{js}
POST /users/
```

## Get comments made by user

```{js}
GET /users/{user_name}/comments/
```

#### Parameters

| Name      | Type    | In   | Description |
|-----------|---------|------|-------------|
| user_name | string  | path |             |

#### Default Response

```{js}
Status: 200 OK
```

```{js}
{
   "user_id": 3,
   "total_comments": 1,
   "comments": [
      {
         "id": 3,
         "recipe_id": 1,
         "content": "Simmer dean"
      }
   ]
}
```

---

## Get recipes submitted by user

```{js}
GET /users/{user_name}/recipes/
```

#### Parameters

| Name      | Type    | In   | Description |
|-----------|---------|------|-------------|
| user_name | string  | path |             |

#### Default Response

```{js}
Status: 200 OK
```

```{js}
{
   "user_id": 1,
   "total_recipes": 1,
   "recipes": [
      {
         "id": 1,
         "name": "Test Recipe 1",
         "submitted_on": "2021-01-20"
      }
   ]
}
```

---


# Recipes

## Get list of recipes

```{js}
GET /recipes/
```

#### Parameters

None

#### Default Response

```{js}
Status: 200 OK
```

```{js}
{
   "recipes":[
      {
         "comments":[
            {
               "content":"This is gross",
               "id":1,
               "user":"Test User 2"
            },
            {
               "content":"That's just, like, your opinion, man",
               "id":2,
               "user":"Test User 1"
            },
            {
               "content":"Simmer dean",
               "id":3,
               "user":"Test User 3"
            }
         ],
         "cook_time_minutes":25,
         "id":1,
         "ingredients":[
            {
               "amount":1.0,
               "ingredient":"Canned tomatoes",
               "units":"can"
            },
            {
               "amount":2.0,
               "ingredient":"Cumin powder",
               "units":"Tbsp"
            }
         ],
         "name":"Test Recipe 1",
         "prep_time_minutes":10,
         "steps":[
            {
               "content":"Take out the ingredients",
               "number":1
            },
            {
               "content":"Cook the ingredients",
               "number":2
            },
            {
               "content":"Eat the meal",
               "number":3
            }
         ],
         "user_id":1
      },
   ]
}
```

---

## Get recipe by ID

```{js}
GET /recipe/{recipe_id}
```

#### Parameters

| Name      | Type | In   | Description |
|-----------|------|------|-------------|
| recipe_id | int  | path |             |

#### Default Response

```{js}
Status: 200 OK
```

```{js}
{
   "id": 1,
   "name": "Test Recipe 1",
   "submitted_on": "2021-01-20",
   "prep_time_minutes": 10,
   "cook_time_minutes": 25,
   "user": "TestUser1",
   "ingredients": [
      {
         "ingredient": "Canned tomatoes",
         "amount": 1,
         "units": "can"
      },
      {
         "ingredient": "Cumin powder",
         "amount": 2,
         "units": "Tbsp"
      }
   ],
   "steps": [
      {
         "number": 1,
         "content": "Take out the ingredients"
      },
      {
         "number": 2,
         "content": "Cook the ingredients"
      }
      {
         "number": 3,
         "content": "Eat the meal"
      }
   ]
}
```


# Comments

## Get all comments

## Post comment on recipe

## Get specific comment

## Update comment

## Delete comment

```{js}
DELETE /comments/{comment_id}
```

#### Parameters

| Name       | Type | In   | Description |
|------------|------|------|-------------|
| comment_id | int  | path |             |

#### Default Response

```{js}
Status: 204 No Content
```

---

## Get comments for recipe




```
Users:
    * /users
        * GET: Return list of all users
        * POST:  Add user
    * /users/{user_name}
        * GET: Get information about specific user, including submitted recipes and comments
        * PUT: Update user information
        * DELETE: Delete user


Recipes:
    * /recipes
        * GET: List of all recipes
        * POST: Add recipe
    * /recipes/{recipe_id}
        * GET: Get recipe
        * PUT: Update recipe
        * DELETE: Delete recipe


Ingredients:
    * /ingredients
        * GET: Return list of all ingredients
    * /ingredients/{ingredient_id}
        * GET: List of recipe IDs that use ingredient


Comments:
    * /comments
        * GET: Return list of all comments
        * POST: Add comment (supply user ID and recipe ID)
    * /comments/{comment_id}
        * GET: Get comment
        * PUT: Update comment
        * DELETE: Delete comment
```
